# fly.toml app configuration file generated for secrets-red-firefly-794 on 2025-02-04T12:19:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'anonym'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


  [mounts]
  source = "pg_data"
  destination = "/data"

